os:
  - linux
language: 
  - python
python:
  - "3.4"
install:
  - pip install -r test_requirements.txt --use-mirrors
script:
  - py.test testing_1/unit/model.py --cov testing_1/unit/model.py -v
after_success:
  - coveralls
  
